if(EXISTS "/home/jaking/bustub/build/test/orset_test[1]_tests.cmake")
  include("/home/jaking/bustub/build/test/orset_test[1]_tests.cmake")
else()
  add_test(orset_test_NOT_BUILT orset_test_NOT_BUILT)
endif()
