if(EXISTS "/home/jaking/bustub/build/test/page_guard_test[1]_tests.cmake")
  include("/home/jaking/bustub/build/test/page_guard_test[1]_tests.cmake")
else()
  add_test(page_guard_test_NOT_BUILT page_guard_test_NOT_BUILT)
endif()
