if(EXISTS "/home/jaking/bustub/build/test/txn_index_test[1]_tests.cmake")
  include("/home/jaking/bustub/build/test/txn_index_test[1]_tests.cmake")
else()
  add_test(txn_index_test_NOT_BUILT txn_index_test_NOT_BUILT)
endif()
